name: tatware_tast
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  flutter_translate: ^4.0.2
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  flutter_svg_provider: ^1.0.3
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  solid_bottom_sheet: ^0.1.10
  bottom_bar_with_sheet: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/


